/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StateDesigner.java
 *
 * Created on 16-Dec-2012, 8:59:30 AM
 */
package com.hopkins.rocknrollracing.stateeditor;

import com.hopkins.rocknrollracing.state.CarColor;
import com.hopkins.rocknrollracing.state.CarModel;
import com.hopkins.rocknrollracing.state.CarState;
import com.hopkins.rocknrollracing.views.elements.CarElement;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JSpinner;

/**
 *
 * @author ian
 */
public class StateDesigner extends javax.swing.JFrame {

    private ImagePanel planetImagePanel;
    private ImagePanel carImagePanel;
    private BufferedImage carImage;
    private CarElement carElement;
    
    /** Creates new form StateDesigner */
    public StateDesigner() {
        initComponents();
        initImagePanels();
        initRadioButtons();
        
        carImage = new BufferedImage(CarElement.WIDTH, CarElement.HEIGHT, BufferedImage.TYPE_INT_ARGB);
        carElement = new CarElement();
        try {
            carElement.load();
        } catch (Exception ex) {
            System.err.println(ex.toString());
        }
        
        initValues();
    }
    
    private void initRadioButtons() {
        List<AbstractButton> buttons;
        
        buttons = Collections.list(colorBG.getElements());
        for(int i = 0; i < buttons.size(); i++) {
            AbstractButton button = buttons.get(i);
            CarColor color = CarColor.All[i];
            
            button.setText(color.getName());
            button.setActionCommand("" + i);
        }
        
        buttons = Collections.list(carModelBG.getElements());
        for(int i = 0; i < buttons.size(); i++) {
            AbstractButton button = buttons.get(i);
            CarModel model = CarModel.All[i];
            
            button.setText(model.getName());
            button.setActionCommand("" + i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyBG = new javax.swing.ButtonGroup();
        planetBG = new javax.swing.ButtonGroup();
        divisionBG = new javax.swing.ButtonGroup();
        carModelBG = new javax.swing.ButtonGroup();
        colorBG = new javax.swing.ButtonGroup();
        tiresBG = new javax.swing.ButtonGroup();
        engineBG = new javax.swing.ButtonGroup();
        shocksBG = new javax.swing.ButtonGroup();
        armorBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        difficultyRookie = new javax.swing.JRadioButton();
        difficultyVeteran = new javax.swing.JRadioButton();
        difficultyWarrior = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        money = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        planetPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chargesWeapon = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        chargesBoost = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        chargesDrop = new javax.swing.JSpinner();
        carPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 4, 6, 6));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Difficulty");
        jPanel1.add(jLabel1);

        difficultyBG.add(difficultyRookie);
        difficultyRookie.setSelected(true);
        difficultyRookie.setText("Rookie");
        jPanel1.add(difficultyRookie);

        difficultyBG.add(difficultyVeteran);
        difficultyVeteran.setText("Veteran");
        jPanel1.add(difficultyVeteran);

        difficultyBG.add(difficultyWarrior);
        difficultyWarrior.setText("Warrior");
        jPanel1.add(difficultyWarrior);

        jLabel2.setText("Money");
        jPanel1.add(jLabel2);

        money.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        money.setText("10000");
        money.setAlignmentX(0.0F);
        money.setMargin(new java.awt.Insets(0, 0, 0, 0));
        money.setMaximumSize(new java.awt.Dimension(200, 30));
        jPanel1.add(money);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("Planet");
        jPanel2.add(jLabel3);

        planetBG.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Chem VI");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton1);

        planetBG.add(jRadioButton2);
        jRadioButton2.setText("Drakonis");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton2);

        planetBG.add(jRadioButton3);
        jRadioButton3.setText("Bogmire");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton3);

        planetBG.add(jRadioButton4);
        jRadioButton4.setText("New Mojave");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton4);

        planetBG.add(jRadioButton5);
        jRadioButton5.setText("Nho");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton5);

        planetBG.add(jRadioButton6);
        jRadioButton6.setText("Inferno");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlanetChange(evt);
            }
        });
        jPanel2.add(jRadioButton6);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("Division");
        jPanel3.add(jLabel4);

        divisionBG.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("Division A");
        jPanel3.add(jRadioButton7);

        divisionBG.add(jRadioButton8);
        jRadioButton8.setText("Division B");
        jPanel3.add(jRadioButton8);

        getContentPane().add(jPanel3);

        planetPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        planetPanel.setLayout(new javax.swing.BoxLayout(planetPanel, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(planetPanel);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setText("Car");
        jPanel5.add(jLabel5);

        carModelBG.add(jRadioButton9);
        jRadioButton9.setText("Dirt Devil");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel5.add(jRadioButton9);

        carModelBG.add(jRadioButton10);
        jRadioButton10.setText("Marauder");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel5.add(jRadioButton10);

        carModelBG.add(jRadioButton11);
        jRadioButton11.setText("Air Blade");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel5.add(jRadioButton11);

        carModelBG.add(jRadioButton12);
        jRadioButton12.setText("Battle Trak");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel5.add(jRadioButton12);

        carModelBG.add(jRadioButton13);
        jRadioButton13.setText("Havoc");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel5.add(jRadioButton13);

        getContentPane().add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setText("Color");
        jPanel6.add(jLabel6);

        colorBG.add(jRadioButton14);
        jRadioButton14.setSelected(true);
        jRadioButton14.setText("Black");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton14);

        colorBG.add(jRadioButton15);
        jRadioButton15.setText("Blue");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton15);

        colorBG.add(jRadioButton16);
        jRadioButton16.setText("Red");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton16);

        colorBG.add(jRadioButton17);
        jRadioButton17.setText("Green");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton17);

        colorBG.add(jRadioButton18);
        jRadioButton18.setText("Yellow");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton18);

        colorBG.add(jRadioButton19);
        jRadioButton19.setText("Purple");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton19);

        colorBG.add(jRadioButton21);
        jRadioButton21.setText("Gray");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton21);

        colorBG.add(jRadioButton20);
        jRadioButton20.setText("Orange");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCarChange(evt);
            }
        });
        jPanel6.add(jRadioButton20);

        getContentPane().add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setAlignmentX(0.0F);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jLabel7.setText("Charges");
        jLabel7.setAlignmentX(0.5F);
        jPanel7.add(jLabel7);

        jLabel12.setText("Weapon");
        jPanel7.add(jLabel12);

        chargesWeapon.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        chargesWeapon.setAlignmentX(0.0F);
        chargesWeapon.setMaximumSize(new java.awt.Dimension(100, 30));
        jPanel7.add(chargesWeapon);

        jLabel13.setText("Boost");
        jPanel7.add(jLabel13);

        chargesBoost.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        chargesBoost.setAlignmentX(0.0F);
        chargesBoost.setMaximumSize(new java.awt.Dimension(100, 30));
        jPanel7.add(chargesBoost);

        jLabel14.setText("Drop");
        jPanel7.add(jLabel14);

        chargesDrop.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        chargesDrop.setAlignmentX(0.0F);
        chargesDrop.setMaximumSize(new java.awt.Dimension(100, 30));
        jPanel7.add(chargesDrop);

        getContentPane().add(jPanel7);

        carPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        carPanel.setLayout(new javax.swing.BoxLayout(carPanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(carPanel);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jLabel8.setText("Tires");
        jPanel9.add(jLabel8);

        tiresBG.add(jRadioButton22);
        jRadioButton22.setText("Track Masters");
        jPanel9.add(jRadioButton22);

        tiresBG.add(jRadioButton23);
        jRadioButton23.setText("Road Warriors");
        jPanel9.add(jRadioButton23);

        tiresBG.add(jRadioButton24);
        jRadioButton24.setText("Super Mudwhumpers");
        jPanel9.add(jRadioButton24);

        tiresBG.add(jRadioButton25);
        jRadioButton25.setText("Atlas Power Claws");
        jPanel9.add(jRadioButton25);

        getContentPane().add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jLabel9.setText("Engine");
        jPanel10.add(jLabel9);

        engineBG.add(jRadioButton26);
        jRadioButton26.setText("Cobra Mark VII");
        jPanel10.add(jRadioButton26);

        engineBG.add(jRadioButton27);
        jRadioButton27.setText("War Hammer");
        jPanel10.add(jRadioButton27);

        engineBG.add(jRadioButton28);
        jRadioButton28.setText("Super Charger");
        jPanel10.add(jRadioButton28);

        engineBG.add(jRadioButton29);
        jRadioButton29.setText("Atlas Power Boss");
        jPanel10.add(jRadioButton29);

        getContentPane().add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel10.setText("Shocks");
        jPanel11.add(jLabel10);

        shocksBG.add(jRadioButton30);
        jRadioButton30.setText("Grasshoppers");
        jPanel11.add(jRadioButton30);

        shocksBG.add(jRadioButton31);
        jRadioButton31.setText("Hydrosprings");
        jPanel11.add(jRadioButton31);

        shocksBG.add(jRadioButton32);
        jRadioButton32.setText("Hydro Twinpack");
        jPanel11.add(jRadioButton32);

        shocksBG.add(jRadioButton33);
        jRadioButton33.setText("Atlas Power Lifts");
        jPanel11.add(jRadioButton33);

        getContentPane().add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jLabel11.setText("Armor");
        jPanel12.add(jLabel11);

        armorBG.add(jRadioButton34);
        jRadioButton34.setText("Defender");
        jPanel12.add(jRadioButton34);

        armorBG.add(jRadioButton35);
        jRadioButton35.setText("Rhino Skin");
        jPanel12.add(jRadioButton35);

        armorBG.add(jRadioButton36);
        jRadioButton36.setText("Saber Tooth");
        jPanel12.add(jRadioButton36);

        armorBG.add(jRadioButton37);
        jRadioButton37.setText("Atlas Powerplate");
        jPanel12.add(jRadioButton37);

        getContentPane().add(jPanel12);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/new.png"))); // NOI18N
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNew(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/open.png"))); // NOI18N
        jMenuItem2.setText("Open...");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/save.png"))); // NOI18N
        jMenuItem3.setText("Save");
        jMenu1.add(jMenuItem3);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/save.png"))); // NOI18N
        jMenuItem5.setText("Save As...");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Quit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onQuit(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onQuit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onQuit
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_onQuit

    private void onNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNew
        initValues();
    }//GEN-LAST:event_onNew

    private void onPlanetChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPlanetChange
        setPlanetImage();
    }//GEN-LAST:event_onPlanetChange

    private void onCarChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCarChange
        setCarImage();
    }//GEN-LAST:event_onCarChange

    private void setCarImage() {
        int modelIndex = Integer.parseInt(getSelectedButton(carModelBG).getActionCommand());
        int colorIndex = Integer.parseInt(getSelectedButton(colorBG).getActionCommand());
        
        CarState cs = new CarState();
        cs.frame = 2;
        cs.color = CarColor.All[colorIndex];
        cs.model = CarModel.All[modelIndex];
        
        Graphics g = carImage.createGraphics();
        g.clearRect(0,0, carImage.getWidth(), carImage.getHeight());
        carElement.render(g, cs);
        g.dispose();
        
        carImagePanel.setImage(carImage);
    }
    
    private AbstractButton getSelectedButton(ButtonGroup bg) {
        Enumeration<AbstractButton> buttons = bg.getElements();
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button;
            }
        }
        return null;
    }
    
    private void setPlanetImage() {
        AbstractButton button = getSelectedButton(planetBG);
        String planetName = button.getActionCommand();
        planetName = planetName.toLowerCase().replace(" ", "_");
        String filename = String.format("images/planets/%s.png", planetName);
        
        try {
            InputStream imageIS = this.getClass().getClassLoader().getResourceAsStream(filename);
            BufferedImage image = ImageIO.read(imageIS);
            planetImagePanel.setImage(image);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.toString());
        }
    }
    
    private void initImagePanels() {
        planetImagePanel = new ImagePanel();
        planetImagePanel.setBackground(Color.black);
        planetImagePanel.setScale(2.0);
        planetPanel.add(planetImagePanel);
        
        carImagePanel = new ImagePanel();
        carImagePanel.setBackground(Color.black);
        carImagePanel.setScale(2.0);
        carPanel.add(carImagePanel);
    }
    
    private void initValues() {
        ButtonGroup[] toReset = new ButtonGroup[] {
            difficultyBG, planetBG, divisionBG,
            carModelBG, colorBG, tiresBG,
            engineBG, shocksBG, armorBG
        };
        JSpinner[] spinners = new JSpinner[] {
            chargesWeapon, chargesBoost, chargesDrop
        };
        
        for(ButtonGroup group : toReset) {
            selectFirst(group);
        }
        
        for(JSpinner spinner : spinners) {
            spinner.setValue(1);
        }
        
        money.setText("10000");
        
        setPlanetImage();
        setCarImage();
    }
    
    private void selectFirst(ButtonGroup bg) {
        AbstractButton firstButton = bg.getElements().nextElement();
        firstButton.setSelected(true);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StateDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StateDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StateDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StateDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StateDesigner().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup armorBG;
    private javax.swing.ButtonGroup carModelBG;
    private javax.swing.JPanel carPanel;
    private javax.swing.JSpinner chargesBoost;
    private javax.swing.JSpinner chargesDrop;
    private javax.swing.JSpinner chargesWeapon;
    private javax.swing.ButtonGroup colorBG;
    private javax.swing.ButtonGroup difficultyBG;
    private javax.swing.JRadioButton difficultyRookie;
    private javax.swing.JRadioButton difficultyVeteran;
    private javax.swing.JRadioButton difficultyWarrior;
    private javax.swing.ButtonGroup divisionBG;
    private javax.swing.ButtonGroup engineBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JFormattedTextField money;
    private javax.swing.ButtonGroup planetBG;
    private javax.swing.JPanel planetPanel;
    private javax.swing.ButtonGroup shocksBG;
    private javax.swing.ButtonGroup tiresBG;
    // End of variables declaration//GEN-END:variables
}
