/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrackDesigner.java
 *
 * Created on 15-Dec-2012, 3:31:47 PM
 */
package com.hopkins.rocknrollracing.trackeditor;


import com.hopkins.rocknrollracing.state.track.Track;
import com.hopkins.rocknrollracing.state.track.TrackIO;
import com.hopkins.rocknrollracing.state.track.TrackPiece;
import com.hopkins.rocknrollracing.state.track.TrackPieceType;
import com.hopkins.rocknrollracing.trackeditor.TrackPanel.TileClickEvent;
import com.hopkins.rocknrollracing.views.elements.HudTrackElement;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author ian
 */
public class TrackDesigner extends javax.swing.JFrame {

    protected String curFilename;
    protected Track track;
    protected TrackPanel minimap;
    protected PreviewPanel preview;
    protected HudTrackElement hudTrackElement;
    protected AbstractButton[] buttons;
    protected TrackPiece scratchPiece;
    
    /** Creates new form TrackDesigner */
    public TrackDesigner() {
        curFilename = "";
        initComponents();
        
        try {
            hudTrackElement = new HudTrackElement();
            hudTrackElement.load();
            hudTrackElement.setScale(2.0f);
        } catch (Exception ex) {
            System.err.println("Error loading HUD Track Element: " + ex.toString());
        }
        
        track = new Track();
        setButtonIcons();
        minimap = new TrackPanel(track, hudTrackElement);
        jPanel1.add(minimap);
        minimap.addTileClickListener(new TrackPanel.TileClickListener() {
            public void tileClicked(TileClickEvent event) {
                onTileClick(event);
            }
        });
        
        preview = new PreviewPanel();
        jPanel4.add(preview);
        
        scratchPiece = new TrackPiece();
        setPieceHeight(getCurrentPiece());
        
        setPieceType(TrackPieceType.CornerDownRight);
        
        fileDialog.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".json");
                }
            }
            @Override
            public String getDescription() {
                return "JSON Track Files (*.json)";
            }
        });
        fileDialog.setCurrentDirectory(new File("C:/workspace/Icadev/Javagator-RRR/src/main/resources/tracks"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieceBG = new javax.swing.ButtonGroup();
        fileDialog = new javax.swing.JFileChooser();
        toolBG = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        toolPaint = new javax.swing.JToggleButton();
        toolInspect = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        heightPanel = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jSlider1 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jSlider7 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Designer");
        setResizable(false);

        jLabel1.setText("Track");

        jLabel2.setText("Height");

        jLabel3.setText("Pieces");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Tools");

        jLabel6.setText("Track Notes");

        jScrollPane1.setViewportView(notes);

        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 6, 6));

        pieceBG.add(jToggleButton1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton1);

        pieceBG.add(jToggleButton2);
        jToggleButton2.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton2);

        pieceBG.add(jToggleButton3);
        jToggleButton3.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton3);

        pieceBG.add(jToggleButton4);
        jToggleButton4.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton4);

        pieceBG.add(jToggleButton5);
        jToggleButton5.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton5);

        pieceBG.add(jToggleButton6);
        jToggleButton6.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton6);

        pieceBG.add(jToggleButton7);
        jToggleButton7.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton7);

        pieceBG.add(jToggleButton8);
        jToggleButton8.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton8);

        pieceBG.add(jToggleButton9);
        jToggleButton9.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton9);

        pieceBG.add(jToggleButton10);
        jToggleButton10.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton10);

        pieceBG.add(jToggleButton11);
        jToggleButton11.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton11);

        pieceBG.add(jToggleButton12);
        jToggleButton12.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton12);

        pieceBG.add(jToggleButton14);
        jToggleButton14.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton14);

        pieceBG.add(jToggleButton15);
        jToggleButton15.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton15);

        pieceBG.add(jToggleButton16);
        jToggleButton16.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton16);

        pieceBG.add(jToggleButton17);
        jToggleButton17.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton17);

        pieceBG.add(jToggleButton18);
        jToggleButton18.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton18);

        pieceBG.add(jToggleButton13);
        jToggleButton13.setPreferredSize(new java.awt.Dimension(33, 33));
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPieceChange(evt);
            }
        });
        jPanel2.add(jToggleButton13);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 6, 6));

        toolBG.add(toolPaint);
        toolPaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/paint.png"))); // NOI18N
        toolPaint.setSelected(true);
        toolPaint.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel3.add(toolPaint);

        toolBG.add(toolInspect);
        toolInspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/inspect.png"))); // NOI18N
        toolInspect.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel3.add(toolInspect);

        jLabel7.setText("Preview");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(432, 128));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(4);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setValue(2);
        jSlider2.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider2.setName("1"); // NOI18N
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });
        jSlider2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heightKeyPressed(evt);
            }
        });

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(4);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(2);
        jSlider1.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider1.setName("0"); // NOI18N
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });
        jSlider1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heightKeyPressed(evt);
            }
        });

        jSlider3.setMajorTickSpacing(1);
        jSlider3.setMaximum(4);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.setValue(2);
        jSlider3.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider3.setName("2"); // NOI18N
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });
        jSlider3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heightKeyPressed(evt);
            }
        });

        jSlider4.setMajorTickSpacing(1);
        jSlider4.setMaximum(4);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setPaintTicks(true);
        jSlider4.setSnapToTicks(true);
        jSlider4.setValue(2);
        jSlider4.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider4.setName("3"); // NOI18N
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });

        jSlider5.setMajorTickSpacing(1);
        jSlider5.setMaximum(4);
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setPaintTicks(true);
        jSlider5.setSnapToTicks(true);
        jSlider5.setValue(2);
        jSlider5.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider5.setName("4"); // NOI18N
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });

        jSlider6.setMajorTickSpacing(1);
        jSlider6.setMaximum(4);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setPaintTicks(true);
        jSlider6.setSnapToTicks(true);
        jSlider6.setValue(2);
        jSlider6.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider6.setName("5"); // NOI18N
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });

        jSlider7.setMajorTickSpacing(1);
        jSlider7.setMaximum(4);
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setPaintTicks(true);
        jSlider7.setSnapToTicks(true);
        jSlider7.setValue(2);
        jSlider7.setMaximumSize(new java.awt.Dimension(25, 23));
        jSlider7.setName("6"); // NOI18N
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightChanged(evt);
            }
        });

        javax.swing.GroupLayout heightPanelLayout = new javax.swing.GroupLayout(heightPanel);
        heightPanel.setLayout(heightPanelLayout);
        heightPanelLayout.setHorizontalGroup(
            heightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        heightPanelLayout.setVerticalGroup(
            heightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(heightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Obstacle");

        jLabel8.setText("Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Arrow Forward", "Arrow Backward", "Puddle" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Center", "Bottom" }));

        jLabel9.setText("Position:");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/new.png"))); // NOI18N
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNew(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/open.png"))); // NOI18N
        jMenuItem2.setText("Open...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOpen(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/save.png"))); // NOI18N
        jMenuItem5.setText("Save");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSave(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/save.png"))); // NOI18N
        jMenuItem3.setText("Save As...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSaveAs(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Quit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onQuit(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(heightPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(heightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void setButtonIcons() {
        
        // copy into an array of buttons
        List<AbstractButton> listButtons = Collections.list(pieceBG.getElements());
        
        buttons = new AbstractButton[listButtons.size()];
        listButtons.toArray(buttons);
        
        
        TrackPieceType[] types = TrackPieceType.values();
        
        for(int i = 0; i < 18; i++) {
            AbstractButton button = buttons[i];
            TrackPieceType type = types[(i+1) % 18];
            
            BufferedImage iconBuffer = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
            Graphics g = iconBuffer.getGraphics();
            hudTrackElement.renderPiece(g, 0, 0, type);
            g.dispose();
            ImageIcon icon = new ImageIcon(iconBuffer);
            
            button.setIcon(icon);
            button.setToolTipText(type.toString());
            button.setActionCommand(type.toString());
        }
    }
    
    private void onQuit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onQuit
        System.err.println("quit");
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_onQuit

    private void doSave() {
        track.setNotes(notes.getText());
        try {
            TrackIO.saveTrack(curFilename, track);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
            ex.printStackTrace(System.err);
        }
    }
    
    private void onSaveAs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSaveAs
        fileDialog.setDialogType(JFileChooser.SAVE_DIALOG);
        if (fileDialog.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        curFilename = fileDialog.getSelectedFile().getAbsolutePath();
        if (!curFilename.endsWith(".json")) {
            curFilename += ".json";
        }
        
        doSave();
    }//GEN-LAST:event_onSaveAs

    private void onOpen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOpen

        fileDialog.setDialogType(JFileChooser.OPEN_DIALOG);
        if (fileDialog.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        curFilename = fileDialog.getSelectedFile().getAbsolutePath();
        try {
            track = TrackIO.loadTrack(curFilename);
            minimap.setTrack(track);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
            ex.printStackTrace(System.err);
        }
        
        // load the JSON into the track
        notes.setText(track.getNotes());
        minimap.repaint();
    }//GEN-LAST:event_onOpen

    private void onNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNew
        curFilename = "";
        track.clear();
        notes.setText(track.getNotes());
        minimap.repaint();
    }//GEN-LAST:event_onNew

    private void onSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSave
        if (curFilename.length() == 0) {
            onSaveAs(evt);
        } else {
            doSave();
        }
    }//GEN-LAST:event_onSave

    private void onPieceChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPieceChange
        TrackPiece p = getCurrentPiece();
        p.setType(getPieceType());
        minimap.repaint();
        preview.setPiece(p);
    }//GEN-LAST:event_onPieceChange

    private void heightChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightChanged
        JSlider slider = (JSlider) evt.getSource();
        TrackPiece p = getCurrentPiece();
        int value = slider.getValue();
        int index = Integer.parseInt(slider.getName());
        
        if (p.getType().isMultiHeight()) {
            p.setHeight(index, value);
        } else {
            p.setHeightAll(value);
            setPieceHeight(p);
        }
        preview.setPiece(p);
    }//GEN-LAST:event_heightChanged

    private void heightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightKeyPressed
        JSlider slider = (JSlider) evt.getSource();
        TrackPiece p = getCurrentPiece();
        int value = slider.getValue();
        int index = Integer.parseInt(slider.getName());
        if (evt.getKeyChar() == ' ') {
            p.setHeightAll(value);
            setPieceHeight(p);
        }
    }//GEN-LAST:event_heightKeyPressed

    private TrackPiece getCurrentPiece() {
        if (getToolType() == ToolType.Paint) {
            return scratchPiece;
        } else {
            return track.getPiece(minimap.getSelectedTile().x, minimap.getSelectedTile().y);
        }
    }
    
    private ToolType getToolType() {
        if (toolPaint.isSelected()) {
            return ToolType.Paint;
        } else {
            return ToolType.Inspect;
        }
    }
    
    private TrackPieceType getPieceType() {
        return TrackPieceType.valueOf(pieceBG.getSelection().getActionCommand());
    }
    
    private void setPieceType(TrackPieceType type) {
        int index = type.ordinal();
        buttons[(index + 17) % 18].setSelected(true);
        
        TrackPiece p = new TrackPiece();
        p.setType(getPieceType());
        preview.setPiece(p);
    }
    
    private void setPieceHeight(TrackPiece piece) {
        int max = heightPanel.getComponentCount();
        for(int i = 0; i < max; i++) {
            JSlider slider = (JSlider) heightPanel.getComponent(i);
            int height = piece.getHeight(i);
            if (slider.getValue() != height) {
                slider.setValue(height);
            }
        }
    }
    
    private void onTileClick(TrackPanel.TileClickEvent evt) {
        switch (getToolType()) {
            case Paint:
                // set the piece
                getCurrentPiece().setType(getPieceType());
                break;
            case Inspect:
                // load the piece
                TrackPiece piece = getCurrentPiece();
                setPieceHeight(piece);
                setPieceType(piece.getType());
                break;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackDesigner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackDesigner().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileDialog;
    private javax.swing.JPanel heightPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JTextPane notes;
    private javax.swing.ButtonGroup pieceBG;
    private javax.swing.ButtonGroup toolBG;
    private javax.swing.JToggleButton toolInspect;
    private javax.swing.JToggleButton toolPaint;
    // End of variables declaration//GEN-END:variables
}
